export const providerDetails = [
  {
    id: 'siteground',
    name: 'Siteground',
    description: 'Premium web hosting with excellent performance and support',
    website: 'https://www.siteground.com',
    logo: 'https://www.google.com/s2/favicons?domain=siteground.com&sz=64',
    founded: '2004',
    headquarters: 'Limassol, Cyprus',
    locations: ['United States', 'Netherlands', 'United Kingdom', 'Singapore'],
    features: ['SSD Storage', 'Daily Backups', '24/7 Support', 'CloudFlare CDN'],
    priceRange: '$100 - $200',
    platforms: ['KVM'],
    specialties: ['WordPress Hosting', 'E-commerce', 'Enterprise Solutions'],
    rating: 4.8,
    customers: '2,800,000+',
    datacenters: 6
  },
  {
    id: 'greengeeks',
    name: 'GreenGeeks',
    description: 'Eco-friendly web hosting with renewable energy commitment',
    website: 'https://www.greengeeks.com',
    logo: 'https://www.google.com/s2/favicons?domain=greengeeks.com&sz=64',
    founded: '2008',
    headquarters: 'Los Angeles, CA',
    locations: ['United States', 'Canada', 'Netherlands'],
    features: ['Eco-Friendly', 'Free SSL', 'Free Migration', 'cPanel/WHM'],
    priceRange: '$39.95 - $59.95',
    platforms: ['KVM'],
    specialties: ['Green Hosting', 'Shared Hosting', 'VPS Hosting'],
    rating: 4.5,
    customers: '600,000+',
    datacenters: 3
  },
  {
    id: 'hostarmada',
    name: 'HostArmada',
    description: 'Fast and reliable hosting with cutting-edge technology',
    website: 'https://hostarmada.com',
    logo: 'https://www.google.com/s2/favicons?domain=hostarmada.com&sz=64',
    founded: '2019',
    headquarters: 'Newark, DE',
    locations: ['United States', 'United Kingdom', 'India', 'Australia'],
    features: ['CloudLinux', 'Free Setup', 'LiteSpeed', 'Free SSL'],
    priceRange: '$41.21+',
    platforms: ['OpenVZ', 'KVM'],
    specialties: ['Cloud Hosting', 'WordPress Hosting', 'VPS Hosting'],
    rating: 4.9,
    customers: '50,000+',
    datacenters: 9
  },
  {
    id: 'scalahosting',
    name: 'ScalaHosting',
    description: 'Innovative hosting solutions with custom SPanel control panel',
    website: 'https://www.scalahosting.com',
    logo: 'https://www.google.com/s2/favicons?domain=scalahosting.com&sz=64',
    founded: '2007',
    headquarters: 'Dallas, TX',
    locations: ['United States', 'Europe'],
    features: ['SPanel Control Panel', 'Free SSL', 'SShield Security', 'Free Migration'],
    priceRange: '$9.95+',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'Cloud Hosting', 'Managed WordPress'],
    rating: 4.9,
    customers: '700,000+',
    datacenters: 3
  },
  {
    id: 'fastcomet',
    name: 'FastComet',
    description: 'Global hosting provider with emphasis on speed and security',
    website: 'https://www.fastcomet.com',
    logo: 'https://www.google.com/s2/favicons?domain=fastcomet.com&sz=64',
    founded: '2013',
    headquarters: 'San Francisco, CA',
    locations: ['United States', 'United Kingdom', 'Netherlands', 'Singapore', 'Japan'],
    features: ['Free Migration', 'Cloudflare CDN', 'Daily Backups', 'SSD Storage'],
    priceRange: '$46.95+',
    platforms: ['KVM'],
    specialties: ['Cloud Hosting', 'WordPress Hosting', 'VPS Hosting'],
    rating: 4.8,
    customers: '750,000+',
    datacenters: 11
  },
  {
    id: 'bandwagonhost',
    name: 'BandwagonHost',
    description: 'Affordable VPS hosting with premium network connectivity',
    website: 'https://bandwagonhost.com',
    logo: 'https://www.google.com/s2/favicons?domain=bandwagonhost.com&sz=64',
    founded: '2012',
    headquarters: 'Vancouver, Canada',
    locations: ['United States', 'Canada', 'Netherlands', 'Hong Kong'],
    features: ['CN2 GIA Network', 'KiwiVM Control Panel', 'Snapshots', 'Migration Tools'],
    priceRange: '$16.88 - $169.99',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'China-Optimized Routes', 'Premium Networks'],
    rating: 4.7,
    customers: '100,000+',
    datacenters: 10
  },
  {
    id: 'hostinger',
    name: 'Hostinger',
    description: 'Affordable hosting solutions with modern technology stack',
    website: 'https://www.hostinger.com',
    logo: 'https://www.google.com/s2/favicons?domain=hostinger.com&sz=64',
    founded: '2004',
    headquarters: 'Kaunas, Lithuania',
    locations: ['United States', 'United Kingdom', 'Lithuania', 'Singapore', 'Brazil'],
    features: ['NVMe SSD', 'AI Assistant', 'Weekly Backups', 'Global CDN'],
    priceRange: '$3.95 - $15.95',
    platforms: ['KVM'],
    specialties: ['Shared Hosting', 'VPS Hosting', 'Cloud Hosting'],
    rating: 4.6,
    customers: '2,000,000+',
    datacenters: 8
  },
  {
    id: 'interserver',
    name: 'Interserver',
    description: 'Reliable hosting with price lock guarantee and unlimited features',
    website: 'https://www.interserver.net',
    logo: 'https://www.google.com/s2/favicons?domain=interserver.net&sz=64',
    founded: '1999',
    headquarters: 'Secaucus, NJ',
    locations: ['United States'],
    features: ['Price Lock Guarantee', 'Free Migration', 'Unlimited Storage', '99.9% Uptime'],
    priceRange: '$6.00 - $18.00',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'Dedicated Servers', 'Web Hosting'],
    rating: 4.5,
    customers: '250,000+',
    datacenters: 4
  },
  {
    id: 'namehero',
    name: 'Namehero',
    description: 'High-performance hosting with a focus on speed and scalability.',
    website: 'https://www.namehero.com',
    logo: 'https://www.google.com/s2/favicons?domain=namehero.com&sz=64',
    founded: '2015',
    headquarters: 'Kansas City, MO',
    locations: ['United States', 'Netherlands'],
    features: ['NVMe Storage', 'LiteSpeed Server', 'Free cPanel', '24/7 Support'],
    priceRange: '$27.98 - $54.98',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'Reseller Hosting', 'WordPress Hosting'],
    rating: 4.8,
    customers: '100,000+',
    datacenters: 2
  },
  {
    id: 'dreamhost',
    name: 'Dreamhost',
    description: 'Employee-owned web hosting company with a focus on open-source.',
    website: 'https://www.dreamhost.com',
    logo: 'https://www.google.com/s2/favicons?domain=dreamhost.com&sz=64',
    founded: '1997',
    headquarters: 'Brea, CA',
    locations: ['United States'],
    features: ['Unlimited Bandwidth', 'Free SSL', 'Custom Control Panel', '100% Uptime Guarantee'],
    priceRange: '$10.00 - $80.00',
    platforms: ['KVM'],
    specialties: ['Managed VPS', 'WordPress Hosting', 'Shared Hosting'],
    rating: 4.7,
    customers: '1,500,000+',
    datacenters: 2
  },
  {
    id: 'hostpapa',
    name: 'Hostpapa',
    description: 'Canadian-based web hosting providing solutions for small businesses.',
    website: 'https://www.hostpapa.com',
    logo: 'https://www.google.com/s2/favicons?domain=hostpapa.com&sz=64',
    founded: '2006',
    headquarters: 'Burlington, Canada',
    locations: ['Canada', 'United States', 'Europe'],
    features: ['cPanel', 'Free Migration', '24/7 Support', '30-day Guarantee'],
    priceRange: '$19.99 - $249.99',
    platforms: ['KVM'],
    specialties: ['Small Business Hosting', 'VPS Hosting', 'Green Hosting'],
    rating: 4.4,
    customers: '500,000+',
    datacenters: 3
  },
  {
    id: 'cloudways',
    name: 'Cloudways',
    description: 'Managed cloud hosting platform for developers and e-commerce.',
    website: 'https://www.cloudways.com',
    logo: 'https://www.google.com/s2/favicons?domain=cloudways.com&sz=64',
    founded: '2011',
    headquarters: 'Mosta, Malta',
    locations: ['Global (via DO, AWS, GCE)'],
    features: ['Choice of IaaS', 'Managed Security', 'Free SSL', '24/7/365 Support'],
    priceRange: '$11.00 - $1000+',
    platforms: ['KVM'],
    specialties: ['Managed Cloud Hosting', 'E-commerce', 'Agencies & Developers'],
    rating: 4.7,
    customers: '250,000+',
    datacenters: 65
  },
  {
    id: 'chemicloud',
    name: 'Chemicloud',
    description: 'Independently owned web host with a focus on reliability and support.',
    website: 'https://www.chemicloud.com',
    logo: 'https://www.google.com/s2/favicons?domain=chemicloud.com&sz=64',
    founded: '2016',
    headquarters: 'Newark, DE',
    locations: ['United States', 'United Kingdom', 'Australia', 'Singapore', 'Germany'],
    features: ['LiteSpeed Server', 'Free cPanel', 'Daily Backups', 'Proactive Monitoring'],
    priceRange: '$19.95 - $79.95',
    platforms: ['KVM'],
    specialties: ['Shared Hosting', 'VPS Hosting', 'Reseller Hosting'],
    rating: 5.0,
    customers: '70,000+',
    datacenters: 11
  },
  {
    id: 'dmit',
    name: 'DMIT',
    description: 'High-performance VPS hosting with a focus on premium network routes.',
    website: 'https://www.dmit.io',
    logo: 'https://www.google.com/s2/favicons?domain=dmit.io&sz=64',
    founded: '2018',
    headquarters: 'Hong Kong',
    locations: ['United States', 'Japan', 'Hong Kong'],
    features: ['AMD EPYC CPUs', 'NVMe SSD', 'Premium Network', 'DDoS Protection'],
    priceRange: '$14.90+',
    platforms: ['KVM'],
    specialties: ['High-Performance VPS', 'Asia-Optimized Routes', 'Enterprise Hosting'],
    rating: 4.6,
    customers: 'N/A',
    datacenters: 3
  },
  {
    id: 'hostingcom',
    name: 'Hosting.com',
    description: 'Premium web hosting services, formerly A2 Hosting.',
    website: 'https://www.hosting.com',
    logo: 'https://www.google.com/s2/favicons?domain=hosting.com&sz=64',
    founded: '2001',
    headquarters: 'Ann Arbor, MI',
    locations: ['United States', 'Netherlands', 'Singapore'],
    features: ['24/7 Guru Crew Support', 'Free Account Migration', 'Money-Back Guarantee', '99.9% Uptime Commitment'],
    priceRange: '$4.99+',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'WordPress Hosting', 'Dedicated Servers'],
    rating: 4.2,
    customers: 'N/A',
    datacenters: 3
  },
  {
    id: 'a2hosting',
    name: 'A2 Hosting',
    description: 'Blazing fast web hosting with a focus on speed and reliability.',
    website: 'https://www.a2hosting.com',
    logo: 'https://www.google.com/s2/favicons?domain=a2hosting.com&sz=64',
    founded: '2001',
    headquarters: 'Ann Arbor, MI',
    locations: ['United States', 'Netherlands', 'Singapore'],
    features: ['Turbo Servers (20X Faster)', 'Free SSL', '24/7 Guru Crew Support', 'Anytime Money-Back Guarantee'],
    priceRange: '$29.99 - $79.99',
    platforms: ['KVM'],
    specialties: ['Performance Hosting', 'Developer Friendly', 'VPS Hosting'],
    rating: 4.7,
    customers: '500,000+',
    datacenters: 4
  },
  {
    id: 'bluehost',
    name: 'Bluehost',
    description: 'One of the largest and most popular web hosting companies, recommended by WordPress.org.',
    website: 'https://www.bluehost.com',
    logo: 'https://www.google.com/s2/favicons?domain=bluehost.com&sz=64',
    founded: '2003',
    headquarters: 'Orem, UT',
    locations: ['United States', 'India', 'China'],
    features: ['Free Domain Name', 'Free SSL Certificate', '1-Click WordPress Install', '24/7 Support'],
    priceRange: '$24.99 - $59.99',
    platforms: ['KVM'],
    specialties: ['WordPress Hosting', 'Shared Hosting', 'VPS Hosting'],
    rating: 4.2,
    customers: '2,000,000+',
    datacenters: 6
  },
  {
    id: 'inmotion',
    name: 'InMotion Hosting',
    description: 'A well-established hosting provider known for its reliable performance and excellent customer support.',
    website: 'https://www.inmotionhosting.com',
    logo: 'https://www.google.com/s2/favicons?domain=inmotionhosting.com&sz=64',
    founded: '2001',
    headquarters: 'Los Angeles, CA',
    locations: ['United States (East & West)'],
    features: ['Free SSL', 'SSD Storage', 'cPanel', '90-Day Money-Back Guarantee'],
    priceRange: '$14.99 - $169.99',
    platforms: ['KVM'],
    specialties: ['VPS Hosting', 'Dedicated Servers', 'Business Hosting'],
    rating: 4.5,
    customers: '300,000+',
    datacenters: 2
  },
  {
    id: 'liquidweb',
    name: 'Liquid Web',
    description: 'Premium managed hosting for mission-critical sites, with a focus on speed and security.',
    website: 'https://www.liquidweb.com',
    logo: 'https://www.google.com/s2/favicons?domain=liquidweb.com&sz=64',
    founded: '1997',
    headquarters: 'Lansing, MI',
    locations: ['United States', 'Netherlands'],
    features: ['100% Network and Power Uptime Guarantee', 'Proactive Monitoring', 'Fully Managed Hosting', 'World-Class Support'],
    priceRange: '$15 - $349',
    platforms: ['KVM'],
    specialties: ['Managed VPS', 'Dedicated Servers', 'Cloud Hosting', 'HIPAA Compliant Hosting'],
    rating: 4.9,
    customers: '45,000+',
    datacenters: 5
  },
  {
    id: 'namecheap',
    name: 'Namecheap',
    description: 'Known primarily for domain registration, Namecheap also offers affordable and reliable hosting services.',
    website: 'https://www.namecheap.com',
    logo: 'https://www.google.com/s2/favicons?domain=namecheap.com&sz=64',
    founded: '2000',
    headquarters: 'Phoenix, AZ',
    locations: ['United States', 'United Kingdom', 'Netherlands'],
    features: ['Free Domain Privacy', 'Free SSL', 'cPanel', 'Website Builder'],
    priceRange: '$6.88 - $17.88',
    platforms: ['KVM'],
    specialties: ['Domain Names', 'Shared Hosting', 'VPS Hosting'],
    rating: 4.3,
    customers: '11,000,000+',
    datacenters: 3
  },
]; 