import type { VPSPlan } from '@/types/vps';

export const mockVPSData: VPSPlan[] = [
  // Siteground - UPDATED
  {
    id: 'siteground-jump-start',
    provider: 'Siteground',
    planName: 'Jump Start',
    type: 'Managed Cloud Hosting',
    price: 100.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '40 GB SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps', // Standard, not explicitly listed but typical
    location: { country: 'United States', city: 'Multiple', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Fully Managed', 'Daily Backups', 'Free CDN', '24/7 Priority Support', 'Dedicated IP'],
    url: 'https://www.siteground.com/cloud-hosting.htm',
    providerSlug: 'siteground',
  },
  {
    id: 'siteground-business',
    provider: 'Siteground',
    planName: 'Business',
    type: 'Managed Cloud Hosting',
    price: 200.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '8 Cores',
    ram: '12 GB',
    storage: '80 GB SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps', // Standard, not explicitly listed but typical
    location: { country: 'United Kingdom', city: 'London', countryCode: 'gb', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['Auto-scaling', 'Staging Environment', 'White-Label Reselling', 'Collaboration Tools'],
    url: 'https://www.siteground.com/cloud-hosting.htm',
    providerSlug: 'siteground',
  },
  {
    id: 'siteground-business-plus',
    provider: 'Siteground',
    planName: 'Business Plus',
    type: 'Managed Cloud Hosting',
    price: 300.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '12 Cores',
    ram: '16 GB',
    storage: '120 GB SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps', // Standard, not explicitly listed but typical
    location: { country: 'Netherlands', city: 'Amsterdam', countryCode: 'nl', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['Advanced Priority Support', 'Dynamic Caching', 'Free SSL', 'Git Integration'],
    url: 'https://www.siteground.com/cloud-hosting.htm',
    providerSlug: 'siteground',
  },
  {
    id: 'siteground-super-power',
    provider: 'Siteground',
    planName: 'Super Power',
    type: 'Managed Cloud Hosting',
    price: 400.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '16 Cores',
    ram: '20 GB',
    storage: '160 GB SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps', // Standard, not explicitly listed but typical
    location: { country: 'Singapore', city: 'Singapore', countryCode: 'sg', region: 'Asia' },
    virtualization: 'KVM',
    includedFeatures: ['Premium Power', 'Easy Client Management', 'WP-CLI', 'Free Private DNS'],
    url: 'https://www.siteground.com/cloud-hosting.htm',
    providerSlug: 'siteground',
  },

  // GreenGeeks - UPDATED
  {
    id: 'greengeeks-4gb',
    provider: 'Greengeeks',
    planName: '4GB RAM Plan',
    type: 'Managed VPS',
    price: 69.95,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 vCPU',
    ram: '4 GB',
    storage: '75 GB SSD',
    bandwidth: '10 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'United States', city: 'Chicago', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['cPanel Included', 'Free SSL Certificate', 'Free Website Transfer', 'Managed Support', '300% Green Energy Match'],
    url: 'https://www.greengeeks.com/vps-hosting',
    providerSlug: 'greengeeks',
  },
  {
    id: 'greengeeks-8gb',
    provider: 'Greengeeks',
    planName: '8GB RAM Plan',
    type: 'Managed VPS',
    price: 129.95,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '6 vCPU',
    ram: '8 GB',
    storage: '150 GB SSD',
    bandwidth: '10 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'Canada', city: 'Montreal', countryCode: 'ca', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Best Seller', 'Free Softaculous License', 'Pro-active Monitoring', 'Advanced Security'],
    url: 'https://www.greengeeks.com/vps-hosting',
    providerSlug: 'greengeeks',
  },
  {
    id: 'greengeeks-16gb',
    provider: 'Greengeeks',
    planName: '16GB RAM Plan',
    type: 'Managed VPS',
    price: 179.95,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '6 vCPU',
    ram: '16 GB',
    storage: '250 GB SSD',
    bandwidth: '10 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'Netherlands', city: 'Amsterdam', countryCode: 'nl', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['High Power', 'Free cPanel Migration', 'RAID-10 SSD', '24/7 Expert Support'],
    url: 'https://www.greengeeks.com/vps-hosting',
    providerSlug: 'greengeeks',
  },

  // HostArmada - UPDATED
  {
    id: 'hostarmada-web-shuttle',
    planName: 'Web Shuttle',
    provider: 'Hostarmada',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 29.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Dallas', countryCode: 'us', region: 'North America' },
    cpu: '1 Core',
    ram: '2 GB',
    storage: '50 GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    includedFeatures: ['Fully Managed', 'Free cPanel', 'Daily Backups', 'LiteSpeed Server', 'Root Access'],
    url: 'https://hostarmada.com/cloud-ssd-vps-hosting/',
    providerSlug: 'hostarmada'
  },
  {
    id: 'hostarmada-web-voyager',
    planName: 'Web Voyager',
    provider: 'Hostarmada',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 35.73,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Germany', city: 'Frankfurt', countryCode: 'de', region: 'Europe' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '80 GB NVMe',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    includedFeatures: ['5 Free cPanel Accounts', 'KVM Virtualization', 'Free Backups', 'WAF & Malware Protection'],
    url: 'https://hostarmada.com/cloud-ssd-vps-hosting/',
    providerSlug: 'hostarmada'
  },
  {
    id: 'hostarmada-web-raider',
    planName: 'Web Raider',
    provider: 'Hostarmada',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 46.73,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Singapore', city: 'Singapore', countryCode: 'sg', region: 'Asia' },
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '160 GB NVMe',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    includedFeatures: ['Enhanced Caching', 'Free Private DNS', 'Imunify360 Protection', 'Full Root Access'],
    url: 'https://hostarmada.com/cloud-ssd-vps-hosting/',
    providerSlug: 'hostarmada'
  },
  {
    id: 'hostarmada-site-carrier',
    planName: 'Site Carrier',
    provider: 'Hostarmada',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 74.23,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Australia', city: 'Sydney', countryCode: 'au', region: 'Oceania' },
    cpu: '6 Cores',
    ram: '16 GB',
    storage: '320 GB NVMe',
    bandwidth: '8 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    includedFeatures: ['Top-tier Performance', 'Free cPanel/WHM', 'Dedicated IP', '24/7 Support'],
    url: 'https://hostarmada.com/cloud-ssd-vps-hosting/',
    providerSlug: 'hostarmada'
  },
  
  // ScalaHosting - UPDATED
  {
    id: 'scalahosting-build-1',
    planName: 'Build #1',
    provider: 'Scalahosting',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 29.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Dallas', countryCode: 'us', region: 'North America' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '50 GB NVMe SSD',
    bandwidth: 'Unmetered',
    networkSpeed: '1 Gbps',
    includedFeatures: ['SPanel Control Panel', 'Daily Disaster Recovery Backups', 'SShield Security', 'Dedicated IP'],
    url: 'https://www.scalahosting.com/managed-vps-hosting.html',
    providerSlug: 'scalahosting'
  },
  {
    id: 'scalahosting-build-2',
    planName: 'Build #2',
    provider: 'Scalahosting',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 63.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Europe', city: 'London', countryCode: 'gb', region: 'Europe' },
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '100 GB NVMe SSD',
    bandwidth: 'Unmetered',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Free Website Migration', '24/7/365 Managed Support', 'HTTP/3 Support', 'SWordPress Manager'],
    url: 'https://www.scalahosting.com/managed-vps-hosting.html',
    providerSlug: 'scalahosting'
  },
  {
    id: 'scalahosting-build-3',
    planName: 'Build #3',
    provider: 'Scalahosting',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 121.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'New York', countryCode: 'us', region: 'North America' },
    cpu: '8 Cores',
    ram: '16 GB',
    storage: '160 GB NVMe SSD',
    bandwidth: 'Unmetered',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Pro Spamexperts', 'Blacklist Monitoring', 'Scalable Resources', 'Free SSL Certificates'],
    url: 'https://www.scalahosting.com/managed-vps-hosting.html',
    providerSlug: 'scalahosting'
  },
  {
    id: 'scalahosting-build-4',
    planName: 'Build #4',
    provider: 'Scalahosting',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 179.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Dallas', countryCode: 'us', region: 'North America' },
    cpu: '12 Cores',
    ram: '24 GB',
    storage: '240 GB NVMe SSD',
    bandwidth: 'Unmetered',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Highest Performance', 'White-Label SPanel', 'HTTP/3 Enabled', 'NVMe Storage'],
    url: 'https://www.scalahosting.com/managed-vps-hosting.html',
    providerSlug: 'scalahosting'
  },

  // FastComet - UPDATED
  {
    id: 'fastcomet-cloud-1',
    planName: 'Cloud 1',
    provider: 'Fastcomet',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 46.16,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Dallas', countryCode: 'us', region: 'North America' },
    cpu: '1 Core',
    ram: '2 GB',
    storage: '50 GB SSD',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['cPanel/WHM', 'Free Migration', 'Daily Backups', 'Server Monitoring'],
    url: 'https://www.fastcomet.com/cloud-vps-hosting',
    providerSlug: 'fastcomet'
  },
  {
    id: 'fastcomet-cloud-2',
    planName: 'Cloud 2',
    provider: 'Fastcomet',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 53.86,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Germany', city: 'Frankfurt', countryCode: 'de', region: 'Europe' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '80 GB SSD',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['cPanel/WHM', 'Free Migration', 'Daily Backups', 'Server Monitoring'],
    url: 'https://www.fastcomet.com/cloud-vps-hosting',
    providerSlug: 'fastcomet'
  },
  {
    id: 'fastcomet-cloud-3',
    planName: 'Cloud 3',
    provider: 'Fastcomet',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 69.26,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United Kingdom', city: 'London', countryCode: 'gb', region: 'Europe' },
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '160 GB SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['cPanel/WHM', 'Free Migration', 'Daily Backups', 'Server Monitoring'],
    url: 'https://www.fastcomet.com/cloud-vps-hosting',
    providerSlug: 'fastcomet'
  },
  {
    id: 'fastcomet-cloud-4',
    planName: 'Cloud 4',
    provider: 'Fastcomet',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 107.76,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Singapore', city: 'Singapore', countryCode: 'sg', region: 'Asia' },
    cpu: '6 Cores',
    ram: '16 GB',
    storage: '320 GB SSD',
    bandwidth: '8 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['cPanel/WHM', 'Free Migration', 'Daily Backups', 'Server Monitoring'],
    url: 'https://www.fastcomet.com/cloud-vps-hosting',
    providerSlug: 'fastcomet'
  },

  // Namehero - UPDATED
  {
    id: 'namehero-starter-cloudshield',
    provider: 'Namehero',
    planName: 'Starter CloudShield',
    type: 'Managed Cloud VPS',
    price: 23.70,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 AMD CPU Cores',
    ram: '4 GB',
    storage: '150GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '10Gbps', // Assumed standard from other providers
    location: { country: 'United States', city: 'Multiple', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['FREE Imunify360 Security', 'FREE CloudLinux OS', 'FREE LiteSpeed Webserver', 'FREE cPanel Control Panel'],
    url: 'https://www.namehero.com/vps-hosting.php',
    providerSlug: 'namehero',
  },
  {
    id: 'namehero-plus-cloudshield',
    provider: 'Namehero',
    planName: 'Plus CloudShield',
    type: 'Managed Cloud VPS',
    price: 32.43,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '6 AMD CPU Cores',
    ram: '8 GB',
    storage: '250GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '10Gbps', // Assumed standard from other providers
    location: { country: 'United States', city: 'Multiple', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['FREE Imunify360 Security', 'FREE LiteSpeed Webserver', 'FREE cPanel Control Panel', 'FREE WHMCS'],
    url: 'https://www.namehero.com/vps-hosting.php',
    providerSlug: 'namehero',
  },
  {
    id: 'namehero-turbo-cloudshield',
    provider: 'Namehero',
    planName: 'Turbo CloudShield',
    type: 'Managed Cloud VPS',
    price: 40.23,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '8 AMD CPU Cores',
    ram: '16 GB',
    storage: '450GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '10Gbps', // Assumed standard from other providers
    location: { country: 'Netherlands', city: 'Amsterdam', countryCode: 'nl', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['FREE Imunify360 Security', 'FREE LiteSpeed Webserver', 'FREE cPanel Control Panel', 'FREE WHMCS'],
    url: 'https://www.namehero.com/vps-hosting.php',
    providerSlug: 'namehero',
  },
  {
    id: 'namehero-business-cloudshield',
    provider: 'Namehero',
    planName: 'Business CloudShield',
    type: 'Managed Cloud VPS',
    price: 49.03,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '10 AMD CPU Cores',
    ram: '32 GB',
    storage: '500GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '10Gbps', // Assumed standard from other providers
    location: { country: 'Netherlands', city: 'Amsterdam', countryCode: 'nl', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['FREE Imunify360 Security', 'FREE LiteSpeed Webserver', 'FREE cPanel Control Panel', 'FREE WHMCS'],
    url: 'https://www.namehero.com/vps-hosting.php',
    providerSlug: 'namehero',
  },

  // DreamHost
  {
    id: 'dreamhost-1',
    planName: 'VPS Basic',
    provider: 'Dreamhost',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 13.75,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Ashburn', countryCode: 'us', region: 'North America' },
    cpu: '1 Core',
    ram: '1 GB',
    storage: '30 GB SSD',
    bandwidth: 'Unlimited',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Managed Performance', 'Scalable RAM', 'Unlimited Websites', 'Free SSL'],
    url: 'https://www.dreamhost.com/vps-hosting/',
    providerSlug: 'dreamhost'
  },
  {
    id: 'dreamhost-2',
    planName: 'VPS Business',
    provider: 'Dreamhost',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 27.50,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Ashburn', countryCode: 'us', region: 'North America' },
    cpu: '2 Cores',
    ram: '2 GB',
    storage: '60 GB SSD',
    bandwidth: 'Unlimited',
    networkSpeed: '1 Gbps',
    includedFeatures: ['High-Speed SSDs', 'US-Based Support', '100% Uptime Guarantee', 'Unlimited Bandwidth'],
    url: 'https://www.dreamhost.com/vps-hosting/',
    providerSlug: 'dreamhost'
  },
  {
    id: 'dreamhost-3',
    planName: 'VPS Professional',
    provider: 'Dreamhost',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 55.00,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Ashburn', countryCode: 'us', region: 'North America' },
    cpu: '4 Cores',
    ram: '4 GB',
    storage: '120 GB SSD',
    bandwidth: 'Unlimited',
    networkSpeed: '1 Gbps',
    includedFeatures: ['For High-Traffic Sites', 'Scalable Resources', 'Email Accounts', 'Custom Panel'],
    url: 'https://www.dreamhost.com/vps-hosting/',
    providerSlug: 'dreamhost'
  },
  {
    id: 'dreamhost-4',
    planName: 'VPS Performance',
    provider: 'Dreamhost',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 57.99,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Ashburn', countryCode: 'us', region: 'North America' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '120 GB NVMe',
    bandwidth: 'Unlimited',
    networkSpeed: '1 Gbps',
    includedFeatures: [
      "Unlimited Websites",
      "Add Domains Easily",
      "1-Click Install WordPress",
      "Free SSL Certificate",
      "Unlimited Email",
      "Business Advisor",
      "24/7 Support",
      "Global Data Centers"
    ],
    url: 'https://www.dreamhost.com/vps-hosting/',
    providerSlug: 'dreamhost'
  },

  // HostPapa
  {
    id: 'hostpapa-1',
    planName: 'Mercury',
    provider: 'Hostpapa',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 19.99,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Los Angeles', countryCode: 'us', region: 'North America' },
    cpu: '4 Cores',
    ram: '2 GB',
    storage: '60 GB SSD',
    bandwidth: '1 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Fully Managed', 'cPanel/WHM', 'Root Access', '2 IP Addresses'],
    url: 'https://www.hostpapa.com/vps-hosting/',
    providerSlug: 'hostpapa'
  },
  {
    id: 'hostpapa-2',
    planName: 'Venus',
    provider: 'Hostpapa',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 59.99,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Canada', city: 'Toronto', countryCode: 'ca', region: 'North America' },
    cpu: '4 Cores',
    ram: '4 GB',
    storage: '125 GB SSD',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Enhanced Security', 'Free Migration', 'SolusVM Panel', 'RAID-10 SSD'],
    url: 'https://www.hostpapa.com/vps-hosting/',
    providerSlug: 'hostpapa'
  },
  {
    id: 'hostpapa-3',
    planName: 'Jupiter',
    provider: 'Hostpapa',
    type: 'Managed VPS',
    virtualization: 'KVM',
    price: 109.99,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Europe', city: 'Amsterdam', countryCode: 'nl', region: 'Europe' },
    cpu: '8 Cores',
    ram: '8 GB',
    storage: '250 GB SSD',
    bandwidth: '2.5 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['More Power', 'Proactive Monitoring', '3 IP Addresses', 'Enterprise-grade Servers'],
    url: 'https://www.hostpapa.com/vps-hosting/',
    providerSlug: 'hostpapa'
  },

  // Cloudways
  {
    id: 'cloudways-1',
    planName: 'DO 1GB',
    provider: 'Cloudways',
    type: 'Managed Cloud',
    virtualization: 'KVM',
    price: 11.00,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'New York', countryCode: 'us', region: 'North America' },
    cpu: '1 Core',
    ram: '1 GB',
    storage: '25 GB SSD',
    bandwidth: '1 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Managed DigitalOcean', '24/7/365 Support', 'Free SSL', 'Automated Backups'],
    url: 'https://www.cloudways.com/en/digitalocean-hosting.php',
    providerSlug: 'cloudways'
  },
  {
    id: 'cloudways-2',
    planName: 'Vultr HF 2GB',
    provider: 'Cloudways',
    type: 'Managed Cloud',
    virtualization: 'KVM',
    price: 28.00,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Germany', city: 'Frankfurt', countryCode: 'de', region: 'Europe' },
    cpu: '1 Core',
    ram: '2 GB',
    storage: '64 GB NVMe SSD',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Managed Vultr HF', 'Staging Environment', 'Team Management', 'Cloudflare CDN'],
    url: 'https://www.cloudways.com/en/vultr-hosting.php',
    providerSlug: 'cloudways'
  },
  {
    id: 'cloudways-3',
    planName: 'AWS 4GB',
    provider: 'Cloudways',
    type: 'Managed Cloud',
    virtualization: 'Xen',
    price: 88.57,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'N. Virginia', countryCode: 'us', region: 'North America' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '20 GB SSD',
    bandwidth: '2 TB',
    networkSpeed: '5 Gbps',
    includedFeatures: ['Managed AWS', 'Pay As You Go', 'Advanced Caching', 'Free Migration'],
    url: 'https://www.cloudways.com/en/aws-hosting.php',
    providerSlug: 'cloudways'
  },

  // Chemicloud
  {
    id: 'chemicloud-1',
    planName: 'CVPS 1',
    provider: 'Chemicloud',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 19.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'United States', city: 'Dallas', countryCode: 'us', region: 'North America' },
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '80 GB NVMe SSD',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Fully Managed', 'LiteSpeed Server', 'Free cPanel', '99.99% Uptime'],
    url: 'https://www.chemicloud.com/vps-hosting/',
    providerSlug: 'chemicloud'
  },
  {
    id: 'chemicloud-2',
    planName: 'CVPS 2',
    provider: 'Chemicloud',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 29.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Germany', city: 'Frankfurt', countryCode: 'de', region: 'Europe' },
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '160 GB NVMe SSD',
    bandwidth: '5 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['24/7 Priority Support', 'Free Daily Backups', 'Proactive Monitoring', '1-click Softaculous'],
    url: 'https://www.chemicloud.com/vps-hosting/',
    providerSlug: 'chemicloud'
  },
  {
    id: 'chemicloud-3',
    planName: 'CVPS 3',
    provider: 'Chemicloud',
    type: 'Managed Cloud VPS',
    virtualization: 'KVM',
    price: 49.95,
    currency: 'USD',
    frequency: 'Monthly',
    location: { country: 'Australia', city: 'Sydney', countryCode: 'au', region: 'Oceania' },
    cpu: '6 Cores',
    ram: '12 GB',
    storage: '240 GB NVMe SSD',
    bandwidth: '6 TB',
    networkSpeed: '1 Gbps',
    includedFeatures: ['Top-Tier Performance', 'Imunify360 Security', 'Free Website Migrations', '15-day money-back'],
    url: 'https://www.chemicloud.com/vps-hosting/',
    providerSlug: 'chemicloud'
  },

  // BandwagonHost - UPDATED
  {
    id: 'bandwagonhost-cn2-gia-20g',
    provider: 'Bandwagonhost',
    planName: 'SPECIAL 20G KVM PROMO V5 - CN2 GIA',
    type: 'CN2 GIA VPS',
    price: 16.66, // Calculated from $49.99 quarterly
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '1 GB',
    storage: '20 GB RAID-10 SSD',
    bandwidth: '1000 GB',
    networkSpeed: '2.5 Gbps',
    location: { country: 'United States', city: 'Los Angeles', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['China Telecom CN2 GIA', 'Free Automatic Backups', 'Free Snapshots', 'KiwiVM Control Panel'],
    url: 'https://bandwagonhost.com/cart.php?gid=1',
    providerSlug: 'bandwagonhost',
  },
  {
    id: 'bandwagonhost-cn2-gia-80g',
    provider: 'Bandwagonhost',
    planName: 'SPECIAL 80G KVM PROMO V5 - CN2 GIA',
    type: 'CN2 GIA VPS',
    price: 56.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '4 GB',
    storage: '80 GB RAID-10 SSD',
    bandwidth: '3000 GB',
    networkSpeed: '2.5 Gbps',
    location: { country: 'Japan', city: 'Osaka', countryCode: 'jp', region: 'Asia' },
    virtualization: 'KVM',
    includedFeatures: ['China Telecom CN2 GIA', 'Free Automatic Backups', 'Free Snapshots', 'KiwiVM Control Panel'],
    url: 'https://bandwagonhost.com/cart.php?gid=1',
    providerSlug: 'bandwagonhost',
  },
  {
    id: 'bandwagonhost-dubai-20g',
    provider: 'Bandwagonhost',
    planName: 'SPECIAL 20G KVM PROMO V5 - DUBAI',
    type: 'Dubai VPS',
    price: 19.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '1 GB',
    storage: '20 GB RAID-10 SSD',
    bandwidth: '500 GB',
    networkSpeed: '1 Gbps',
    location: { country: 'United Arab Emirates', city: 'Dubai', countryCode: 'ae', region: 'Middle East' },
    virtualization: 'KVM',
    includedFeatures: ['Free Automatic Backups', 'Free Snapshots', 'KiwiVM Control Panel'],
    url: 'https://bandwagonhost.com/cart.php?gid=1',
    providerSlug: 'bandwagonhost',
  },
  {
    id: 'bandwagonhost-dubai-80g',
    provider: 'Bandwagonhost',
    planName: 'SPECIAL 80G KVM PROMO V5 - DUBAI',
    type: 'Dubai VPS',
    price: 56.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '4 GB',
    storage: '80 GB RAID-10 SSD',
    bandwidth: '2000 GB',
    networkSpeed: '1 Gbps',
    location: { country: 'United Arab Emirates', city: 'Dubai', countryCode: 'ae', region: 'Middle East' },
    virtualization: 'KVM',
    includedFeatures: ['Free Automatic Backups', 'Free Snapshots', 'KiwiVM Control Panel'],
    url: 'https://bandwagonhost.com/cart.php?gid=1',
    providerSlug: 'bandwagonhost',
  },

  // Hostinger - UPDATED
  {
    id: 'hostinger-kvm-2',
    provider: 'Hostinger',
    planName: 'KVM 2',
    type: 'KVM VPS',
    price: 6.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '8 GB',
    storage: '100 GB NVMe',
    bandwidth: '2 TB', // Assuming from existing data, as it's a common value
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'United States', city: 'Multiple', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'AI Assistant', 'Weekly Backups', 'DDoS Protection'],
    url: 'https://www.hostinger.com/vps-hosting',
    providerSlug: 'hostinger',
  },
  {
    id: 'hostinger-kvm-4',
    provider: 'Hostinger',
    planName: 'KVM 4',
    type: 'KVM VPS',
    price: 9.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '16 GB',
    storage: '200 GB NVMe',
    bandwidth: '4 TB', // Extrapolated based on KVM 2 plan
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'United Kingdom', city: 'London', countryCode: 'gb', region: 'Europe' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'AI Assistant', 'Weekly Backups', 'DDoS Protection'],
    url: 'https://www.hostinger.com/vps-hosting',
    providerSlug: 'hostinger',
  },

  // Interserver - UPDATED
  {
    id: 'interserver-linux-vps-1',
    provider: 'Interserver',
    planName: 'Linux VPS - 1 Slice',
    type: 'Linux VPS',
    price: 3.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '1 Cores',
    ram: '2GB',
    storage: '40GB SSD',
    bandwidth: '2TB',
    networkSpeed: '10Gbps',
    location: { country: 'United States', city: 'Secaucus', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Price Lock Guarantee', '10Gbps Port Speed', 'Self Healing Hardware', '99.9% Uptime'],
    url: 'https://www.interserver.net/vps/',
    providerSlug: 'interserver',
  },
  {
    id: 'interserver-linux-vps-4',
    provider: 'Interserver',
    planName: 'Linux VPS - 4 Slices',
    type: 'Linux VPS',
    price: 12.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '8GB',
    storage: '160GB SSD',
    bandwidth: '8TB',
    networkSpeed: '10Gbps',
    location: { country: 'United States', city: 'Secaucus', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Price Lock Guarantee', '10Gbps Port Speed', 'Self Healing Hardware', '99.9% Uptime'],
    url: 'https://www.interserver.net/vps/',
    providerSlug: 'interserver',
  },
  {
    id: 'interserver-storage-vps-1',
    provider: 'Interserver',
    planName: 'Storage VPS - 1 Slice',
    type: 'Storage VPS',
    price: 3.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '1 Cores',
    ram: '2GB',
    storage: '1TB SATA',
    bandwidth: '2TB',
    networkSpeed: '10Gbps',
    location: { country: 'United States', city: 'Secaucus', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Price Lock Guarantee', '10Gbps Port Speed', 'Large Storage', 'RAID-6'],
    url: 'https://www.interserver.net/vps/',
    providerSlug: 'interserver',
  },
  {
    id: 'interserver-storage-vps-4',
    provider: 'Interserver',
    planName: 'Storage VPS - 4 Slices',
    type: 'Storage VPS',
    price: 12.00,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '8GB',
    storage: '4TB SATA',
    bandwidth: '8TB',
    networkSpeed: '10Gbps',
    location: { country: 'United States', city: 'Secaucus', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Price Lock Guarantee', '10Gbps Port Speed', 'Large Storage', 'RAID-6'],
    url: 'https://www.interserver.net/vps/',
    providerSlug: 'interserver',
  },

  // DMIT
  {
    id: 'dmit-pvm-lax-tiny',
    provider: 'DMIT',
    planName: 'PVM.LAX.Tiny',
    type: 'High-Performance VPS',
    price: 6.90,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '1 vCore',
    ram: '0.75 GB',
    storage: '10G SSD',
    bandwidth: '1000 GB',
    networkSpeed: '2 Gbps',
    location: {
      country: 'United States',
      city: 'Los Angeles',
      countryCode: 'us',
      region: 'North America'
    },
    virtualization: 'KVM',
    includedFeatures: ['1 IPv4', '1 IPv6/64', 'Premium Network'],
    url: 'https://www.dmit.io/',
    providerSlug: 'dmit',
  },
  {
    id: 'dmit-pvm-lax-micro',
    provider: 'DMIT',
    planName: 'PVM.LAX.Micro',
    type: 'High-Performance VPS',
    price: 14.90,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 vCore',
    ram: '1.5 GB',
    storage: '20G SSD',
    bandwidth: '2000 GB',
    networkSpeed: '4 Gbps',
    location: {
      country: 'United States',
      city: 'Los Angeles',
      countryCode: 'us',
      region: 'North America'
    },
    virtualization: 'KVM',
    includedFeatures: ['1 IPv4', '1 IPv6/64', 'Premium Network'],
    url: 'https://www.dmit.io/',
    providerSlug: 'dmit',
  },
  {
    id: 'dmit-pvm-lax-medium',
    provider: 'DMIT',
    planName: 'PVM.LAX.Medium',
    type: 'High-Performance VPS',
    price: 29.90,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 vCore',
    ram: '3 GB',
    storage: '40G SSD',
    bandwidth: '4000 GB',
    networkSpeed: '6 Gbps',
    location: {
      country: 'United States',
      city: 'Los Angeles',
      countryCode: 'us',
      region: 'North America'
    },
    virtualization: 'KVM',
    includedFeatures: ['1 IPv4', '1 IPv6/64', 'Premium Network'],
    url: 'https://www.dmit.io/',
    providerSlug: 'dmit',
  },
  {
    id: 'hostingcom-runway-1',
    provider: 'Hosting.com',
    planName: 'Runway 1',
    type: 'Unmanaged VPS',
    price: 4.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '1 Core',
    ram: '1 GB',
    storage: '25 GB NVMe',
    bandwidth: '1 TB',
    networkSpeed: '1 Gbps', // Assumed standard
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'cPanel Available', 'Choice of OS', 'DDoS Protection'],
    url: 'https://www.hosting.com/vps-hosting/unmanaged/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-runway-2',
    provider: 'Hosting.com',
    planName: 'Runway 2',
    type: 'Unmanaged VPS',
    price: 7.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '1 Core',
    ram: '2 GB',
    storage: '50 GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'cPanel Available', 'Choice of OS', 'DDoS Protection'],
    url: 'https://www.hosting.com/vps-hosting/unmanaged/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-runway-4',
    provider: 'Hosting.com',
    planName: 'Runway 4',
    type: 'Unmanaged VPS',
    price: 12.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '100 GB NVMe',
    bandwidth: '3 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'cPanel Available', 'Choice of OS', 'DDoS Protection'],
    url: 'https://www.hosting.com/vps-hosting/unmanaged/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-supersonic-8',
    provider: 'Hosting.com',
    planName: 'Supersonic 8',
    type: 'Unmanaged VPS',
    price: 24.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '200 GB NVMe',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Full Root Access', 'cPanel Available', 'Choice of OS', 'DDoS Protection'],
    url: 'https://www.hosting.com/vps-hosting/unmanaged/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-lift-4',
    provider: 'Hosting.com',
    planName: 'Lift 4',
    type: 'Managed VPS',
    price: 34.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '2 Cores',
    ram: '4 GB',
    storage: '75 GB NVMe',
    bandwidth: '2 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Fully Managed', 'cPanel Included', 'Free Migrations', 'Security Monitoring'],
    url: 'https://www.hosting.com/vps-hosting/managed/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-lift-8',
    provider: 'Hosting.com',
    planName: 'Lift 8',
    type: 'Managed VPS',
    price: 54.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '4 Cores',
    ram: '8 GB',
    storage: '150 GB NVMe',
    bandwidth: '3 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Fully Managed', 'cPanel Included', 'Free Migrations', 'Security Monitoring'],
    url: 'https://www.hosting.com/vps-hosting/managed/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-lift-16',
    provider: 'Hosting.com',
    planName: 'Lift 16',
    type: 'Managed VPS',
    price: 64.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '6 Cores',
    ram: '16 GB',
    storage: '250 GB NVMe',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Fully Managed', 'cPanel Included', 'Free Migrations', 'Security Monitoring'],
    url: 'https://www.hosting.com/vps-hosting/managed/',
    providerSlug: 'hostingcom',
  },
  {
    id: 'hostingcom-mach-32',
    provider: 'Hosting.com',
    planName: 'Mach 32',
    type: 'Managed VPS',
    price: 74.99,
    currency: 'USD',
    frequency: 'Monthly',
    cpu: '8 Cores',
    ram: '32 GB',
    storage: '450 GB NVMe',
    bandwidth: '4 TB',
    networkSpeed: '1 Gbps',
    location: { country: 'United States', city: 'Phoenix', countryCode: 'us', region: 'North America' },
    virtualization: 'KVM',
    includedFeatures: ['Fully Managed', 'cPanel Included', 'Free Migrations', 'Security Monitoring'],
    url: 'https://www.hosting.com/vps-hosting/managed/',
    providerSlug: 'hostingcom',
  },
];